<?php

	if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array (
		'key' => 'group_57e2bc6a1d917',
		'title' => 'Content Panel Attributes',
		'fields' => array (
			array (
				'default_value' => '',
				'min' => '',
				'max' => '',
				'step' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'key' => 'field_57e2bc9920054',
				'label' => 'Panel Order',
				'name' => 'panel_order',
				'type' => 'number',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '30',
					'class' => 'small-field',
					'id' => '',
				),
			),
			array (
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'key' => 'field_57f3ea417fdc9',
				'label' => 'Panel Slug (Alternate)',
				'name' => 'panel_slide_slug',
				'type' => 'text',
				'instructions' => 'Enter a 1 or 2 word name for the slide, separated by a hyphen. This is referenced behind the scenes and facilitates the fullscreen navigation of the homepage.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '70',
					'class' => '',
					'id' => '',
				),
			),
			array (
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'key' => 'field_57f6903449c68',
				'label' => 'Panel Label',
				'name' => 'panel_label',
				'type' => 'text',
				'instructions' => 'This is the "marketing-friendly" name of the panel as it appears in the left toolbar; avoid references to content organization (i.e. "footer panel").',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'content_panel',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array (
			0 => 'the_content',
			1 => 'custom_fields',
			2 => 'discussion',
			3 => 'comments',
			4 => 'revisions',
			5 => 'author',
			6 => 'format',
			7 => 'featured_image',
			8 => 'categories',
			9 => 'tags',
			10 => 'send-trackbacks',
		),
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array (
		'key' => 'group_57e2d28896338',
		'title' => 'Content Panel Builder',
		'fields' => array (
			array (
				'layout' => 'horizontal',
				'choices' => array (
					'single_panel' => 'Single Content Panel',
					'slider_panel' => 'Content Panel w/ Horizontal Slides',
					'panel_slide' => 'Content Panel Slide',
				),
				'default_value' => '',
				'other_choice' => 0,
				'save_other_choice' => 0,
				'allow_null' => 0,
				'return_format' => 'value',
				'key' => 'field_57e2fd88abc62',
				'label' => 'Panel Type',
				'name' => 'panel_type',
				'type' => 'radio',
				'instructions' => 'Select and option to display relevant layout/content options.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
			),
			array (
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'key' => 'field_580a8bf98df62',
				'label' => 'Panel Title',
				'name' => 'panel_title',
				'type' => 'text',
				'instructions' => 'Enter a concise name for the panel. Typically, this will be the large, all-caps text on each content panel.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_57e2fd88abc62',
							'operator' => '==',
							'value' => 'single_panel',
						),
					),
					array (
						array (
							'field' => 'field_57e2fd88abc62',
							'operator' => '==',
							'value' => 'slider_panel',
						),
					),
				),
				'wrapper' => array (
					'width' => '50',
					'class' => '',
					'id' => '',
				),
			),
			array (
				'default_value' => '',
				'new_lines' => 'br',
				'maxlength' => '',
				'placeholder' => '',
				'rows' => 4,
				'key' => 'field_57eee152b8a16',
				'label' => 'Panel Marketing Text',
				'name' => 'panel_marketing_text',
				'type' => 'textarea',
				'instructions' => 'Provide a 1-2 sentence text string to accompany the Content Panel title. This text will appear with big, bold text, typically overlaid on an image, so to keep a clean, simple aesthetic, shorter is better.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_57e2fd88abc62',
							'operator' => '==',
							'value' => 'single_panel',
						),
					),
					array (
						array (
							'field' => 'field_57e2fd88abc62',
							'operator' => '==',
							'value' => 'slider_panel',
						),
					),
				),
				'wrapper' => array (
					'width' => '50',
					'class' => '',
					'id' => '',
				),
			),
			array (
				'layout' => 'vertical',
				'choices' => array (
					'image' => 'Image Artwork',
					'color' => 'Solid Color',
					'image_overlay' => 'Image Upload + Solid Color Overlay',
				),
				'default_value' => '',
				'other_choice' => 0,
				'save_other_choice' => 0,
				'allow_null' => 0,
				'return_format' => 'value',
				'key' => 'field_57e2e27a71237',
				'label' => 'Background Style',
				'name' => 'background_style',
				'type' => 'radio',
				'instructions' => 'Select a background style for the content panel.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
			),
			array (
				'default_value' => '',
				'key' => 'field_57f3d95b9166f',
				'label' => 'Background Overlay Color',
				'name' => 'background_overlay_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_57e2e27a71237',
							'operator' => '==',
							'value' => 'image_overlay',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
			),
			array (
				'return_format' => 'array',
				'preview_size' => 'large',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'key' => 'field_57e2d290438e0',
				'label' => 'Background Image Artwork',
				'name' => 'content_panel_image',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_57e2e27a71237',
							'operator' => '==',
							'value' => 'image',
						),
					),
					array (
						array (
							'field' => 'field_57e2e27a71237',
							'operator' => '==',
							'value' => 'image_overlay',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
			),
			array (
				'default_value' => '',
				'key' => 'field_57e2e2db71238',
				'label' => 'Background Color',
				'name' => 'content_panel_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_57e2e27a71237',
							'operator' => '==',
							'value' => 'color',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
			),
			array (
				'sub_fields' => array (
					array (
						'default_value' => '',
						'new_lines' => 'br',
						'maxlength' => '',
						'placeholder' => '',
						'rows' => 1,
						'key' => 'field_57e304c5697a6',
						'label' => 'Content Block Title',
						'name' => 'content_block_title',
						'type' => 'textarea',
						'instructions' => 'The title and/or heading of the content block.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
					array (
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'key' => 'field_57f3fdb585df4',
						'label' => 'Content Block Slug',
						'name' => 'content_block_slug',
						'type' => 'text',
						'instructions' => 'Enter a 1 or 2 word name for the slide, separated by a hyphen. This is referenced behind the scenes and facilitates the fullscreen navigation of the homepage.',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
					array (
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'key' => 'field_57eeea938a9a4',
						'label' => 'Content Block Subheadline',
						'name' => 'content_block_subheadline',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
					array (
						'default_value' => '',
						'new_lines' => '',
						'maxlength' => '',
						'placeholder' => '',
						'rows' => '',
						'key' => 'field_57f3e59efa8ee',
						'label' => 'Content Block Text',
						'name' => 'content_block_text',
						'type' => 'textarea',
						'instructions' => 'Provide 2-3 concise sentences of text content.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
					array (
						'layout' => 'vertical',
						'choices' => array (
							'solid_block' => 'Solid Color',
							'image_block' => 'Background Image',
						),
						'default_value' => '',
						'other_choice' => 0,
						'save_other_choice' => 0,
						'allow_null' => 0,
						'return_format' => 'value',
						'key' => 'field_57f3de644fb99',
						'label' => 'Content Block Background Style',
						'name' => 'content_block_background',
						'type' => 'radio',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
					array (
						'return_format' => 'array',
						'preview_size' => 'large',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
						'key' => 'field_57e40d11df4bd',
						'label' => 'Content Block Background Image',
						'name' => 'content_block_image',
						'type' => 'image',
						'instructions' => 'Upload new background image or select a background image from the media library.',
						'required' => 0,
						'conditional_logic' => array (
							array (
								array (
									'field' => 'field_57f3de644fb99',
									'operator' => '==',
									'value' => 'image_block',
								),
							),
						),
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
					array (
						'default_value' => '',
						'key' => 'field_57e407cc7c571',
						'label' => 'Content Block Color',
						'name' => 'content_block_color',
						'type' => 'color_picker',
						'instructions' => 'Select a color to overlay the background image; the color will also be used for the block\'s icon box, if icon box layout option is selected.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
					array (
						'default_value' => 0,
						'message' => '',
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
						'key' => 'field_57f3dd584fb98',
						'label' => 'Content Block Icon Box',
						'name' => 'content_icon_option',
						'type' => 'true_false',
						'instructions' => 'Check this box to upload an image to be used w/ a colored icon box in the content block.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
					array (
						'return_format' => 'array',
						'preview_size' => 'full',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
						'key' => 'field_57f299c5173b4',
						'label' => 'Content Block Icon',
						'name' => 'content_block_icon',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array (
							array (
								array (
									'field' => 'field_57f3dd584fb98',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
				),
				'min' => 0,
				'max' => 3,
				'layout' => 'row',
				'button_label' => 'Add Panel Content Block',
				'collapsed' => 'field_57e304c5697a6',
				'key' => 'field_57e30438697a5',
				'label' => 'Content Panel Blocks',
				'name' => 'panel_content_blocks',
				'type' => 'repeater',
				'instructions' => 'Populate the top-level slide with content blocks + design elements.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_57e2fd88abc62',
							'operator' => '==',
							'value' => 'slider_panel',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
			),
			array (
				'post_type' => array (
					0 => 'content_panel',
				),
				'taxonomy' => array (
				),
				'allow_null' => 0,
				'multiple' => 1,
				'return_format' => 'object',
				'ui' => 1,
				'key' => 'field_57f3d4c0aca82',
				'label' => 'Content Panel Slides',
				'name' => 'content_panel_slides',
				'type' => 'post_object',
				'instructions' => 'Select child content panels to populate this sliding panel.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_57e2fd88abc62',
							'operator' => '==',
							'value' => 'slider_panel',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'content_panel',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array (
		'key' => 'group_580a84b25b5df',
		'title' => 'Content Panel Slide Builder',
		'fields' => array (
			array (
				'layout' => 'vertical',
				'choices' => array (
					'yes' => 'Add Slide Icon?',
				),
				'default_value' => array (
				),
				'allow_custom' => 0,
				'save_custom' => 0,
				'toggle' => 0,
				'return_format' => 'value',
				'key' => 'field_57feb8cbac3e5',
				'label' => 'Slide Icon Option',
				'name' => 'slide_icon_option',
				'type' => 'checkbox',
				'instructions' => 'Optionally add an icon to the slide for design purposes.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '20',
					'class' => '',
					'id' => '',
				),
			),
			array (
				'return_format' => 'array',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'key' => 'field_57feb92bac3e6',
				'label' => 'Upload/Select Slide Icon',
				'name' => 'panel_slide_icon',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '20',
					'class' => '',
					'id' => '',
				),
			),
			array (
				'default_value' => '',
				'new_lines' => '',
				'maxlength' => '',
				'placeholder' => '',
				'rows' => 2,
				'key' => 'field_580e3d418050c',
				'label' => 'Slide Text Heading',
				'name' => 'slide_text_heading',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '20',
					'class' => '',
					'id' => '',
				),
			),
			array (
				'default_value' => '',
				'new_lines' => 'br',
				'maxlength' => '',
				'placeholder' => '',
				'rows' => 8,
				'key' => 'field_580e367ca89d6',
				'label' => 'Slide Text Content',
				'name' => 'slide_text_content',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '40',
					'class' => '',
					'id' => '',
				),
			),
			array (
				'return_format' => 'array',
				'preview_size' => 'large',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'key' => 'field_580e5f345ef8b',
				'label' => 'Slide Image',
				'name' => 'slide_image',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
			),
			array (
				'layout' => 'vertical',
				'choices' => array (
					'yes' => 'Add Slide Button?',
				),
				'default_value' => array (
				),
				'allow_custom' => 0,
				'save_custom' => 0,
				'toggle' => 0,
				'return_format' => 'value',
				'key' => 'field_580e37e7000ce',
				'label' => 'Slide Button Option',
				'name' => 'slide_button_option',
				'type' => 'checkbox',
				'instructions' => 'Optionally add a button to the slide\'s text content area.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '25',
					'class' => '',
					'id' => '',
				),
			),
			array (
				'post_type' => array (
				),
				'taxonomy' => array (
				),
				'allow_null' => 0,
				'multiple' => 0,
				'allow_archives' => 1,
				'key' => 'field_580e37a0000cd',
				'label' => 'Slide Button Link',
				'name' => 'slide_button_link',
				'type' => 'page_link',
				'instructions' => 'Select an existing page or post to link to the slide\'s button.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '25',
					'class' => '',
					'id' => '',
				),
			),
			array (
				'default_value' => 'learn more',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'key' => 'field_580e3a0c2cdc9',
				'label' => 'Slide Button Text',
				'name' => 'slide_button_text',
				'type' => 'text',
				'instructions' => 'Enter 2-3 words for the button; defaults to "LEARN MORE".',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '25',
					'class' => '',
					'id' => '',
				),
			),
			array (
				'default_value' => 'something goes here
	<em>this line requires the \'em\' tags</em>
	don\'t forget those tags',
				'new_lines' => 'br',
				'maxlength' => '',
				'placeholder' => '',
				'rows' => 3,
				'key' => 'field_58064226efe7c',
				'label' => 'Slide Accent Text',
				'name' => 'slide_accent_text',
				'type' => 'textarea',
				'instructions' => 'Provide a 8-10 word snippet of marketing-speak for the slide.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '25',
					'class' => '',
					'id' => '',
				),
			),
			array (
				'layout' => 'vertical',
				'choices' => array (
					'yes' => 'Add Content Blocks?',
				),
				'default_value' => array (
				),
				'allow_custom' => 0,
				'save_custom' => 0,
				'toggle' => 0,
				'return_format' => 'value',
				'key' => 'field_5818daffa0c49',
				'label' => 'Content Blocks Option',
				'name' => 'content_blocks_option',
				'type' => 'checkbox',
				'instructions' => 'Check this box to add content blocks to the child slide, if necessary',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
			),
			array (
				'sub_fields' => array (
					array (
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'key' => 'field_5818dda196c90',
						'label' => 'Slide Content Block Title',
						'name' => 'slide_content_block_title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
					array (
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'key' => 'field_5818dde496c91',
						'label' => 'Slide Content Block Slug',
						'name' => 'slide_content_block_slug',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
					array (
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'key' => 'field_5818ddf696c92',
						'label' => 'Slide Content Block Subheadline',
						'name' => 'slide_content_block_subheadline',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
					array (
						'default_value' => '',
						'new_lines' => 'br',
						'maxlength' => '',
						'placeholder' => '',
						'rows' => '',
						'key' => 'field_5818de0c96c93',
						'label' => 'Slide Content Block Text',
						'name' => 'slide_content_block_text',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
					array (
						'default_value' => '',
						'key' => 'field_5818de2996c94',
						'label' => 'Slide Content Block Background',
						'name' => 'slide_content_block_background',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
					array (
						'return_format' => 'array',
						'preview_size' => 'post-thumbnail',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
						'key' => 'field_5818de5196c95',
						'label' => 'Slide Content Block Image',
						'name' => 'slide_content_block_image',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
					array (
						'layout' => 'vertical',
						'choices' => array (
							'yes' => 'Add Program Area?',
						),
						'default_value' => array (
						),
						'allow_custom' => 0,
						'save_custom' => 0,
						'toggle' => 0,
						'return_format' => 'value',
						'key' => 'field_58191bd54f9c6',
						'label' => 'Slide Content Block Attributes',
						'name' => 'slide_content_block_attributes',
						'type' => 'checkbox',
						'instructions' => 'Check this box to reveal options specific to creating project-related content blocks.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
					array (
						'layout' => 'horizontal',
						'choices' => array (
							'food_systems' => 'Food Systems',
							'environmental_change' => 'Environmental Change',
							'urbanization' => 'Urbanization',
						),
						'default_value' => '',
						'other_choice' => 0,
						'save_other_choice' => 0,
						'allow_null' => 0,
						'return_format' => 'value',
						'key' => 'field_58191c045d632',
						'label' => 'Program Area',
						'name' => 'program_area',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array (
							array (
								array (
									'field' => 'field_58191bd54f9c6',
									'operator' => '==',
									'value' => 'yes',
								),
							),
						),
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
				),
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => 'Add Slide Content Block',
				'collapsed' => 'field_5818dda196c90',
				'key' => 'field_5818da9082c9d',
				'label' => 'Slide Content Blocks',
				'name' => 'slide_content_blocks',
				'type' => 'repeater',
				'instructions' => 'Populate the child-level slide with content blocks + design elements.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_5818daffa0c49',
							'operator' => '==',
							'value' => 'yes',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'content_panel',
				),
				array (
					'param' => 'page_type',
					'operator' => '==',
					'value' => 'child',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array (
		'key' => 'group_5818c67c36bae',
		'title' => 'News Post Attributes',
		'fields' => array (
			array (
				'default_value' => '',
				'placeholder' => '',
				'key' => 'field_5818c6896ba16',
				'label' => 'News Story Link',
				'name' => 'news_story_link',
				'type' => 'url',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
				array (
					'param' => 'post_category',
					'operator' => '==',
					'value' => 'category:news',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array (
			0 => 'excerpt',
			1 => 'discussion',
			2 => 'comments',
			3 => 'revisions',
			4 => 'author',
			5 => 'format',
			6 => 'featured_image',
			7 => 'tags',
			8 => 'send-trackbacks',
		),
		'active' => 1,
		'description' => '',
	));

	endif;

?>